/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as jokesMutations from "../jokesMutations.js";
import type * as jokesQueries from "../jokesQueries.js";
import type * as mutations_assocs from "../mutations/assocs.js";
import type * as mutations_jokes from "../mutations/jokes.js";
import type * as mutations_models from "../mutations/models.js";
import type * as mutations_policies from "../mutations/policies.js";
import type * as mutations_topics from "../mutations/topics.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  jokesMutations: typeof jokesMutations;
  jokesQueries: typeof jokesQueries;
  "mutations/assocs": typeof mutations_assocs;
  "mutations/jokes": typeof mutations_jokes;
  "mutations/models": typeof mutations_models;
  "mutations/policies": typeof mutations_policies;
  "mutations/topics": typeof mutations_topics;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
