/* tslint:disable */
/* eslint-disable */
/**
 * proto/server.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1TopJokesEntry } from './V1TopJokesEntry';
import {
    V1TopJokesEntryFromJSON,
    V1TopJokesEntryFromJSONTyped,
    V1TopJokesEntryToJSON,
} from './V1TopJokesEntry';

/**
 * GetTopJokesResponse contains the top jokes.
 * @export
 * @interface V1GetTopJokesResponse
 */
export interface V1GetTopJokesResponse {
    /**
     * 
     * @type {Array<V1TopJokesEntry>}
     * @memberof V1GetTopJokesResponse
     */
    entries?: Array<V1TopJokesEntry>;
}

/**
 * Check if a given object implements the V1GetTopJokesResponse interface.
 */
export function instanceOfV1GetTopJokesResponse(value: object): value is V1GetTopJokesResponse {
    return true;
}

export function V1GetTopJokesResponseFromJSON(json: any): V1GetTopJokesResponse {
    return V1GetTopJokesResponseFromJSONTyped(json, false);
}

export function V1GetTopJokesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetTopJokesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(V1TopJokesEntryFromJSON)),
    };
}

export function V1GetTopJokesResponseToJSON(value?: V1GetTopJokesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(V1TopJokesEntryToJSON)),
    };
}

